# Site settings
title: PC Wong
description: Wong Pui Ching, PC

# this means to ignore newlines until "baseurl:"


baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://pcwong.net" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Wong Pui Ching, PC
  image    : assets/images/avatar.jpg
  linkedin : pui-ching-wong-507b62178
  facebook : 
  instagram: 
  email    : contact@pcwong.net

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
